Carsport.Backend/Models/NotificationView.cs
 namespace Carsport.Backend.Models
{
    using Common.Models;
    using System.Web;

    public class NotificationView : Notification
    {
        public HttpPostedFileBase ImageFile { get; set; }
    }
}

Carsport.Backend/Controllers/NotificationsController.cs
namespace Carsport.Backend.Controllers
{
    using Carsport.Backend.Helpers;
    using Carsport.Backend.Models;
    using Carsport.Common.Models;
    using Microsoft.AspNet.Identity;
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    [Authorize(Roles = "Admin")]
    public class NotificationsController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: Notifications
        public async Task<ActionResult> Index()
        {
            return View(await db.Notifications.OrderByDescending(n => n.PublishedOn).ToListAsync());
        }

        // GET: Notifications/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notification notification = await db.Notifications.FindAsync(id);
            if (notification == null)
            {
                return HttpNotFound();
            }
            
            return View(notification);
        }

        // GET: Notifications/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Notifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(NotificationView notificationView)
        {
            if (ModelState.IsValid)
            {
                notificationView.PublishedOn = DateTime.Now.ToLocalTime();
                notificationView.UserId = User.Identity.GetUserId();

                var pic = string.Empty;
                var folder = "~/Content/Notifications";

                if (notificationView.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(notificationView.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var notification = this.ToNotification(notificationView, pic);

                db.Notifications.Add(notification);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(notificationView);
        }

        private Notification ToNotification(NotificationView notificationView, string pic)
        {
            return new Notification
            {
                NotificationId = notificationView.NotificationId,
                Title = notificationView.Title,
                Body = notificationView.Body,
                IsAvailable = notificationView.IsAvailable,
                PublishedOn = notificationView.PublishedOn,
                UserId = notificationView.UserId,
                ImagePath = pic,
            };
        }

        // GET: Notifications/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notification notification = await db.Notifications.FindAsync(id);
            if (notification == null)
            {
                return HttpNotFound();
            }
            var view = this.ToView(notification);
            return View(view);
        }

        private NotificationView ToView(Notification notification)
        {
            return new NotificationView
            {
                NotificationId = notification.NotificationId,
                Title = notification.Title,
                Body = notification.Body,
                IsAvailable = notification.IsAvailable,
                PublishedOn = notification.PublishedOn,
                ImagePath = notification.ImagePath,
            };
        }

        // POST: Notifications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(NotificationView notificationView)
        {
            if (ModelState.IsValid)
            {
                notificationView.PublishedOn = DateTime.Now.ToLocalTime();
                var pic = notificationView.ImagePath;
                var folder = "~/Content/Notifications";

                if (notificationView.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(notificationView.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var notification = this.ToNotification(notificationView, pic);

                db.Entry(notification).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(notificationView);
        }

        // GET: Notifications/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Notification notification = await db.Notifications.FindAsync(id);
            if (notification == null)
            {
                return HttpNotFound();
            }
            return View(notification);
        }

        // POST: Notifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Notification notification = await db.Notifications.FindAsync(id);
            db.Notifications.Remove(notification);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Carsport.Backend/Views/Notifications/Create.cshtml
@model Carsport.Backend.Models.NotificationView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Notifications", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Notification</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Carsport.Backend/Views/Notifications/Delete.cshtml
@model Carsport.Common.Models.Notification

@{
    ViewBag.Title = "Delete";
    var image = "/Content/Media/noimage.png";
    if (!string.IsNullOrEmpty(Model.ImagePath))
    {
        image = Model.ImagePath;
    }
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Notification</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Url.Content(image)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-primary" })
        </div>
    }
</div>

Carsport.Backend/Views/Notifications/Details.cshtml
@model Carsport.Common.Models.Notification

@{
    ViewBag.Title = "Details";
    var image = "/Content/Media/noimage.png";
    if (!string.IsNullOrEmpty(Model.ImagePath))
    {
        image = Model.ImagePath;
    }
}

<h2>Details</h2>

<div>
    <h4>Notification</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Url.Content(image)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NotificationId }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-primary" })
</p>

Carsport.Backend/Views/Notifications/Edit.cshtml
@model Carsport.Backend.Models.NotificationView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Notifications", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Notification</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NotificationId)        
        @Html.HiddenFor(model => model.ImagePath)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(model => model.ImageFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Carsport.Backend/Views/Notifications/Index.cshtml
@model IEnumerable<Carsport.Common.Models.Notification>

@{
    ViewBag.Title = "Notifications";
}

    <h2>Notifications</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAvailable)
        </td>
        <td>
            @if (!string.IsNullOrEmpty(item.ImagePath))
            {
                <img src="@Url.Content(item.ImagePath)" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            } else {
                <img src="@Url.Content("/Content/Media/noimage.png")" alt="Image" style="width:100px;height:150px;max-width: 100%; height: auto;" />
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NotificationId }, new { @class = "btn btn-warning" })
            @Html.ActionLink("Details", "Details", new { id=item.NotificationId }, new { @class = "btn btn-info" })
            @Html.ActionLink("Delete", "Delete", new { id=item.NotificationId }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>