Carsport.Backend/Controllers/CitiesController.cs
namespace Carsport.Backend.Controllers
{
    using Carsport.Backend.Models;
    using Carsport.Common.Models;
    using System.Data.Entity;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: Cities
        public async Task<ActionResult> Index()
        {
            return View(await db.Cities.ToListAsync());
        }

        // GET: Cities/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CityId,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CityId,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = await db.Cities.FindAsync(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            City city = await db.Cities.FindAsync(id);
            db.Cities.Remove(city);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Carsport.Backend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carsport.Backend.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Chat()
        {
            return View();
        }
    }
}

Carsport.Backend/Controllers/RoutesController.cs
namespace Carsport.Backend.Controllers
{
    using Carsport.Backend.Helpers;
    using Carsport.Backend.Models;
    using Carsport.Common.Models;
    using Microsoft.AspNet.Identity;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    [Authorize(Roles = "Admin")]
    public class RoutesController : Controller
    {
        private LocalDataContext db = new LocalDataContext();

        // GET: Routes
        public async Task<ActionResult> Index()
        {
            var routes = db.Routes.Include(r => r.Origin).Include(r => r.Destiny);
            return View(await routes.ToListAsync());
        }

        // GET: Routes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = await db.Routes.FindAsync(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // GET: Routes/Create
        public ActionResult Create()
        {
            ViewBag.OriginID = new SelectList(db.Cities, "CityId", "Name");
            ViewBag.DestinyID = new SelectList(db.Cities, "CityId", "Name");
            return View();
        }

        // POST: Routes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RouteView routeView)
        {
            if (ModelState.IsValid)
            {
                var originEntity = db.Cities.Where(c => c.CityId == routeView.OriginID).ToList();
                var destinyEntity = db.Cities.Where(c => c.CityId == routeView.DestinyID).ToList();

                routeView.Origin = originEntity[0];
                routeView.Destiny = destinyEntity[0];
                routeView.UserId = User.Identity.GetUserId();

                var pic = string.Empty;
                var folder = "~/Content/Routes";

                if (routeView.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(routeView.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var route = this.ToRoute(routeView, pic);

                db.Routes.Add(route);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.OriginID = new SelectList(db.Cities, "CityId", "Name");
            ViewBag.DestinyID = new SelectList(db.Cities, "CityId", "Name");
            return View(routeView);
        }

        // GET: Routes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = await db.Routes.FindAsync(id);
            if (route == null)
            {
                return HttpNotFound();
            }

            ViewBag.OriginID = new SelectList(db.Cities, "CityId", "Name", route.OriginID);
            ViewBag.DestinyID = new SelectList(db.Cities, "CityId", "Name", route.DestinyID);

            var view = this.ToView(route);

            return View(view);
        }

        // POST: Routes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(RouteView routeView)
        {
            if (ModelState.IsValid)
            {
                var originEntity = db.Cities.Where(c => c.CityId == routeView.OriginID).ToList();
                var destinyEntity = db.Cities.Where(c => c.CityId == routeView.DestinyID).ToList();

                routeView.Origin = originEntity[0];
                routeView.Destiny = destinyEntity[0];

                var pic = routeView.ImagePath;
                var folder = "~/Content/Routes";

                if (routeView.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(routeView.ImageFile, folder);
                    pic = $"{folder}/{pic}";
                }

                var route = this.ToRoute(routeView, pic);

                var oldRoute = await db.Routes.FindAsync(route.RouteId);
                oldRoute.Conversations = route.Conversations;
                oldRoute.Date = route.Date;
                oldRoute.Description = oldRoute.Description;
                oldRoute.Destiny = destinyEntity[0];
                oldRoute.DestinyID = route.DestinyID;
                oldRoute.IsDeleted = route.IsDeleted;
                oldRoute.NumSeats = route.NumSeats;
                oldRoute.Origin = originEntity[0];
                oldRoute.OriginID = route.OriginID;
                oldRoute.ImagePath = route.ImagePath;

                db.ChangeTracker.DetectChanges();
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.OriginID = new SelectList(db.Cities, "CityId", "Name", routeView.OriginID);
            ViewBag.DestinyID = new SelectList(db.Cities, "CityId", "Name", routeView.DestinyID);
            return View(routeView);
        }

        // GET: Routes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = await db.Routes.FindAsync(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // POST: Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Route route = await db.Routes.FindAsync(id);
            db.Routes.Remove(route);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private Route ToRoute(RouteView routeView, string pic)
        {
            return new Route
            {
                RouteId = routeView.RouteId,
                OriginID = routeView.OriginID,
                DestinyID = routeView.DestinyID,
                Description = routeView.Description,
                Date = routeView.Date,
                IsDeleted = routeView.IsDeleted,
                UserId = routeView.UserId,
                Origin = routeView.Origin,
                Destiny = routeView.Destiny,
                Conversations = routeView.Conversations,
                NumSeats = routeView.NumSeats,
                Inbackend = true,
                ImagePath = pic,
            };
        }

        private RouteView ToView(Route route)
        {
            return new RouteView
            {
                RouteId = route.RouteId,
                OriginID = route.OriginID,
                DestinyID = route.DestinyID,
                Description = route.Description,
                Date = route.Date,
                IsDeleted = route.IsDeleted,
                UserId = route.UserId,
                Origin = route.Origin,
                Destiny = route.Destiny,
                Inbackend = route.Inbackend,
                Conversations = route.Conversations,
                NumSeats = route.NumSeats,
                ImagePath = route.ImagePath,
            };
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Carsport.Backend/Controllers/UsersController.cs
using Carsport.Backend.Helpers;
using Carsport.Backend.Models;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Carsport.Backend.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index()
        {
            var users = UsersHelper.GetUserList();
            var userView = users.Select(r => new UserView
            {
                UserId = r.Id,
                EMail = r.Email,
                FirstName = r.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.GivenName).ClaimValue,
                LastName = r.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.Name).ClaimValue,
                ImagePath = r.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.Uri) != null ? $"http://movilidaducaapi.somee.com{r.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.Uri).ClaimValue.Substring(1)}" : "http://movilidaducabackend.somee.com/Content/Media/no_profile.png",
                EmailConfirmed = r.EmailConfirmed,
            }).OrderByDescending(u => u.UserId).ToList();
            return View(userView);
        }

        // GET: Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = UsersHelper.GetUserByIdASP(id);
            
            if (user == null)
            {
                return HttpNotFound();
            }

            var userView = this.ToUserView(user);
            return View(userView);
        }

        // GET: Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = UsersHelper.GetUserByIdASP(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var userView = this.ToUserView(user);
            return View(userView);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var user = UsersHelper.GetUserByIdASP(id);
            var isDeletd = UsersHelper.DeleteUser(user.Email, "User");
            var isDeletdClaims = UsersHelper.DeleteUserClaims(user.Email);
            var isDeletdAccount = UsersHelper.DeleteUserAccount(user.Email);
            if(isDeletd && isDeletdAccount && isDeletdAccount)
            {
                return RedirectToAction("Index");
            }
            
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        private UserView ToUserView(ApplicationUser user)
        {
            return new UserView
            {
                UserId = user.Id,
                EMail = user.Email,
                FirstName = user.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.GivenName).ClaimValue,
                LastName = user.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.Name).ClaimValue,
                ImagePath = user.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.Uri) != null ? $"{WebConfigurationManager.AppSettings["apiUrl"]}{user.Claims.FirstOrDefault(c => c.ClaimType == ClaimTypes.Uri).ClaimValue.Substring(1)}" : "http://movilidaducabackend.somee.com/Content/Media/no_profile.png",
                EmailConfirmed = user.EmailConfirmed,
            };
        }
    }
}

Carsport.Backend/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Carsport.Backend/Views/Home/Chat.cshtml
@{
    ViewBag.Title = "Chat";
}
<h2>Chat</h2>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name, message) {
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

Carsport.Backend/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Carsport.Backend/Views/Home/Index.cshtml
@{
                /**/

                ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Carsport</h1>
    <p class="lead">Administration web Carsport mobile aplicaction. You can manage all the information about this mobile app.</p>
</div>

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
<div class="row" style="margin-top:25px;margin-bottom:25px;">
    <div class="col-sm-3" style="margin-bottom:15px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="~/Content/Media/img_users.png" style="width: 18rem;">
            <div class="card-body">
                <h4 class="card-title">Users</h4>
                <p class="card-text">You can manager the users information of mobil application.</p>
                @Html.ActionLink("Go to users", "Index", "Users", new { }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <div class="col-sm-3" style="margin-bottom:15px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="~/Content/Media/img_routes.png" style="width: 18rem;">
            <div class="card-body">
                <h4 class="card-title">Routes</h4>
                <p class="card-text">You can manager the users information of mobil application.</p>
                @Html.ActionLink("Go to routes", "Index", "Routes", new { }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <div class="col-sm-3" style="margin-bottom:15px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="~/Content/Media/img_location.png" style="width: 18rem;">
            <div class="card-body">
                <h4 class="card-title">Cities</h4>
                <p class="card-text">You can manager the users information of mobil application.</p>
                @Html.ActionLink("Go to cities", "Index", "Cities", new { }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <div class="col-sm-3" style="margin-bottom:15px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="~/Content/Media/img_news.png" style="width: 18rem;">
            <div class="card-body">
                <h4 class="card-title">News</h4>
                <p class="card-text">You can manager the users information of mobil application.</p>
                @Html.ActionLink("Go to news", "Index", "Notifications", new { }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <div class="col-sm-3" style="margin-bottom:15px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="~/Content/Media/img_bycicles.png" style="width: 18rem;">
            <div class="card-body">
                <h4 class="card-title">Bycicles</h4>
                <p class="card-text">You can manager the users information of mobil application.</p>
                @Html.ActionLink("Go to bycicles", "Index", "Bycicles", new { }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <div class="col-sm-3" style="margin-bottom:15px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="~/Content/Media/img_stations.png" style="width: 18rem;">
            <div class="card-body">
                <h4 class="card-title">Stations</h4>
                <p class="card-text">You can manager the users information of mobil application.</p>
                @Html.ActionLink("Go to stations", "Index", "Stations", new { }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    <div class="col-sm-3" style="margin-bottom:15px;margin-top:11px">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="~/Content/Media/img_mails.png" style="width: 15.7rem;margin-bottom:10px;">
            <div class="card-body">
                <h4 class="card-title">Mail Template</h4>
                <p class="card-text">You can edit the text of emails.</p>
                @Html.ActionLink("Go to mail template", "Index", "MailTemplates", new { }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
</div>
}